export const styles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    background: '#0f172a',
    color: '#e2e8f0',
    fontFamily: "'Georgia', serif",
  },
  nav: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 2rem',
    borderBottom: '1px solid #1e293b',
    background: '#0f172acc',
    backdropFilter: 'blur(8px)',
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  navLogo: {
    fontSize: '1.25rem',
    fontWeight: 'bold',
    letterSpacing: '0.05em',
    color: '#7dd3fc',
  },
  navBtn: {
    background: 'transparent',
    border: '1px solid #334155',
    color: '#94a3b8',
    padding: '0.4rem 1rem',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    transition: 'all 0.2s',
  },
  hero: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '5rem 2rem',
    maxWidth: '900px',
    margin: '0 auto',
    width: '100%',
    boxSizing: 'border-box',
  },
  heroTitle: {
    fontSize: '3rem',
    fontWeight: 'bold',
    marginBottom: '1rem',
    color: '#f1f5f9',
    letterSpacing: '-0.02em',
  },
  heroSub: {
    fontSize: '1.2rem',
    color: '#94a3b8',
    marginBottom: '2.5rem',
    textAlign: 'center',
  },
  ctaBtn: {
    background: '#3b82f6',
    border: 'none',
    color: '#fff',
    padding: '0.75rem 2rem',
    borderRadius: '8px',
    fontSize: '1rem',
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'background 0.2s',
  },

  // Architecture section
  architectureSection: {
    borderTop: '1px solid #1e293b',
    padding: '5rem 2rem',
    background: '#0a1120',
  },
  architectureInner: {
    maxWidth: '900px',
    margin: '0 auto',
    width: '100%',
    boxSizing: 'border-box',
  },
  architectureEyebrow: {
    fontSize: '0.75rem',
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    color: '#7dd3fc',
    marginBottom: '0.75rem',
  },
  architectureTitle: {
    fontSize: '2rem',
    fontWeight: 'bold',
    color: '#f1f5f9',
    letterSpacing: '-0.02em',
    marginBottom: '1rem',
    marginTop: 0,
  },
  architectureSub: {
    fontSize: '1rem',
    color: '#64748b',
    maxWidth: '560px',
    lineHeight: '1.7',
    marginBottom: '3rem',
  },
  architectureGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: '1.5rem',
  },
  architectureCard: {
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: '10px',
    padding: '1.75rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  architectureStep: {
    fontSize: '0.75rem',
    fontFamily: 'monospace',
    color: '#7dd3fc',
    letterSpacing: '0.1em',
  },
  architectureCardTitle: {
    fontSize: '1.1rem',
    fontWeight: 'bold',
    color: '#f1f5f9',
    margin: 0,
  },
  architectureCardDesc: {
    fontSize: '0.9rem',
    color: '#64748b',
    lineHeight: '1.6',
    margin: 0,
  },

  footer: {
    padding: '1.5rem 2rem',
    borderTop: '1px solid #1e293b',
    textAlign: 'center',
  },
  footerText: {
    color: '#475569',
    fontSize: '0.85rem',
    margin: 0,
  },
  table: {
    width: '100%',
    background: '#1e293b',
    borderRadius: '10px',
    overflow: 'hidden',
    border: '1px solid #334155',
  },
  tableHeader: {
    display: 'flex',
    padding: '0.75rem 1.25rem',
    background: '#0f172a',
    color: '#475569',
    fontSize: '0.8rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    borderBottom: '1px solid #334155',
  },
  tableRow: {
    display: 'flex',
    padding: '0.85rem 1.25rem',
    alignItems: 'center',
    borderBottom: '1px solid #1e293b',
    gap: '0.5rem',
    fontSize: '0.9rem',
  },
  badge: {
    padding: '0.15rem 0.5rem',
    borderRadius: '4px',
    fontSize: '0.75rem',
    fontWeight: 'bold',
    letterSpacing: '0.05em',
    fontFamily: 'monospace',
  },
}